/* Local typecheck stub — real file is generated by `npx convex dev`. Gitignored. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const api: any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const internal: any;
